# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 강혜진
title: 백엔드 엔지니어
email: doghj0105@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java & Spring, cloud native 기술에 특화된 역량을 보유한 4년차 백엔드 엔지니어입니다.


  단순한 기능 구현을 넘어, 서비스의 근간이 되는 플랫폼과 오케스트레이션 시스템을 설계하고 고도화하는 과정에 깊은 관심을 가지고 있습니다. 
  대규모 멀티 테넌시 환경에서 DBaaS 서비스를 개발하며, 수백대의 인스턴스가 안정적으로 가동될 수 있도록 운영 자동화 체계를 구축해 왔습니다.


  개인이 선호하는 기술보다는 <mark>서비스의 안정성과 팀의 운영 효율성</mark>에 기여하는 개발을 지향합니다.


  대규모 트래픽과 복잡한 네트워크 환경에서도 흔들리지 않는 견고한 백엔드 시스템을 만드는 엔지니어로 <mark>성장</mark>하고 싶습니다.

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: kt cloud
        link: https://cloud.kt.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        caption: 2022.06 - 현재
        quote: >
          Cloud, IDC, Network를 통합 제공하는 DX 전문 기업
        description: | # this will include new lines to allow paragraphs
            - 확장성 있는 멀티 DB 엔진 아키텍처 설계 및 개발: PostgreSQL, MySQL, MariaDB, Redis DB 통합 관리 체계 구축


            - 대규모 멀티 테넌시 운영 안정성 확보: 수백대의 DB 인스턴스 자동화 관리 및 가동률 99.9% 달성


            - Java Spring 기반 MSA 구조 설계 및 서비스 개발: 인프라 제어를 위한 비동기 이벤트 기반 컨트롤 플레인 구현

  - title: Key Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: DBaaS 서비스 개발 및 고도화
        quote: >
          대규모 멀티 테넌시 환경에서 DB 엔진의 전체 생명주기를 자동화하는 DBaaS(Database as a Service) 오케스트레이션 플랫폼 개발
        description: | # this will include new lines to allow paragraphs
          - DB 사용자/스키마 관리 API 설계: 멀티 테넌시 환경에서의 권한 격리 및 리소스 제어 API 구현
          - DB 로그 관리 시스템 구축: 대규모 인스턴스에서 발생하는 실시간 로그 수집 및 분석 파이프라인 설계
          - 운영 자동화 엔진 고도화: K8s Operator 패턴을 활용해 프로비저닝, 백업, 복구 등 수동 운영 업무의 90% 자동화
          - 성능 최적화: Redis 캐싱 및 쿼리 튜닝을 통해 대규모 인스턴스 상태 조회 API 성능 개선

  - title: Skill # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        description: |
          - Java, Spring Boot
          - JPA, Querydsl
          - Kafka, Redis
      - layout: left # 새로운 항목임을 나타내는 하이픈 추가
        title: Cloud Native & Infrastructure
        description: |
          - Kubernetes, ArgoCD, Helm, Operator Pattern
          - Linux (Ubuntu), Bash Shell Scripting
      - layout: left
        title: Database
        description: | 
          - PostgreSQL, MySQL, MariaDB
      - layout: left
        title: DevOps & Tools
        description: |
          - Git, GitHub Actions & Jenkins(CI)
          - Jira, Confluence, Slack


  - title: Certificate
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 정보처리기사 / 한국산업인력공단 / 2021.06
      - CKA / The Linux Foundation / 2024.11

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
